[tool.poetry]
name = "knn"
version = "0.1.0"
description = ""
authors = ["Krystian Postek <kpostekk@pjwstk.edu.pl>"]

[tool.poetry.dependencies]
python = ">=3.10"
pandas = "*"
matplotlib = "*"
click = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
